# Example Hyprland config for Mousetrap.
# Update MOUSETRAP_ROOT to point to your mousetrap installation.

$MOUSETRAP_ROOT = /home/pol/src/mousetrap

bind = SUPER, SPACE, exec, $MOUSETRAP_ROOT/packages/linux/activate.sh

submap = mousetrap
binde = , escape, exec, $MOUSETRAP_ROOT/packages/linux/cancel.sh
binde = , 1, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 1
binde = , 2, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 2
binde = , 3, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 3
binde = , 4, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 4
binde = , 5, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 5
binde = , 6, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 6
binde = , 7, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 7
binde = , 8, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 8
binde = , 9, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 9
binde = , 0, exec, $MOUSETRAP_ROOT/packages/linux/select.sh 0
binde = , q, exec, $MOUSETRAP_ROOT/packages/linux/select.sh q
binde = , w, exec, $MOUSETRAP_ROOT/packages/linux/select.sh w
binde = , e, exec, $MOUSETRAP_ROOT/packages/linux/select.sh e
binde = , r, exec, $MOUSETRAP_ROOT/packages/linux/select.sh r
binde = , t, exec, $MOUSETRAP_ROOT/packages/linux/select.sh t
binde = , y, exec, $MOUSETRAP_ROOT/packages/linux/select.sh y
binde = , u, exec, $MOUSETRAP_ROOT/packages/linux/select.sh u
binde = , i, exec, $MOUSETRAP_ROOT/packages/linux/select.sh i
binde = , o, exec, $MOUSETRAP_ROOT/packages/linux/select.sh o
binde = , p, exec, $MOUSETRAP_ROOT/packages/linux/select.sh p
binde = , a, exec, $MOUSETRAP_ROOT/packages/linux/select.sh a
binde = , s, exec, $MOUSETRAP_ROOT/packages/linux/select.sh s
binde = , d, exec, $MOUSETRAP_ROOT/packages/linux/select.sh d
binde = , f, exec, $MOUSETRAP_ROOT/packages/linux/select.sh f
binde = , g, exec, $MOUSETRAP_ROOT/packages/linux/select.sh g
binde = , h, exec, $MOUSETRAP_ROOT/packages/linux/select.sh h
binde = , j, exec, $MOUSETRAP_ROOT/packages/linux/select.sh j
binde = , k, exec, $MOUSETRAP_ROOT/packages/linux/select.sh k
binde = , l, exec, $MOUSETRAP_ROOT/packages/linux/select.sh l
binde = , semicolon, exec, $MOUSETRAP_ROOT/packages/linux/select.sh ';'
binde = , z, exec, $MOUSETRAP_ROOT/packages/linux/select.sh z
binde = , x, exec, $MOUSETRAP_ROOT/packages/linux/select.sh x
binde = , c, exec, $MOUSETRAP_ROOT/packages/linux/select.sh c
binde = , v, exec, $MOUSETRAP_ROOT/packages/linux/select.sh v
binde = , b, exec, $MOUSETRAP_ROOT/packages/linux/select.sh b
binde = , n, exec, $MOUSETRAP_ROOT/packages/linux/select.sh n
binde = , m, exec, $MOUSETRAP_ROOT/packages/linux/select.sh m
binde = , comma, exec, $MOUSETRAP_ROOT/packages/linux/select.sh ,
binde = , period, exec, $MOUSETRAP_ROOT/packages/linux/select.sh .
binde = , slash, exec, $MOUSETRAP_ROOT/packages/linux/select.sh /
submap = reset
