#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_NAME="${APP_NAME:-Mousetrap Dev}"
BUNDLE_ID="${BUNDLE_ID:-com.pablopunk.mousetrap.dev}"
EXECUTABLE_NAME="${EXECUTABLE_NAME:-Mousetrap}"
INSTALL_DIR="${INSTALL_DIR:-/Applications}"
DEV_CODESIGN_IDENTITY="${DEV_CODESIGN_IDENTITY:-Apple Development: Pablo Varela (TUXMN4J924)}"
APP_PATH="$INSTALL_DIR/$APP_NAME.app"

pkill -x "$EXECUTABLE_NAME" || true
sleep 0.2

PREFER_STABLE_DEV_SIGNING="${PREFER_STABLE_DEV_SIGNING:-1}"

APP_NAME="$APP_NAME" \
BUNDLE_ID="$BUNDLE_ID" \
EXECUTABLE_NAME="$EXECUTABLE_NAME" \
INSTALL_DIR="$INSTALL_DIR" \
CODESIGN_IDENTITY="$DEV_CODESIGN_IDENTITY" \
PREFER_STABLE_DEV_SIGNING="$PREFER_STABLE_DEV_SIGNING" \
"$ROOT/scripts/build-app.sh"
open "$APP_PATH"
